# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mosaicpy/gui/main_gui.ui',
# licensing of 'mosaicpy/gui/main_gui.ui' applies.
#
# Created: Sat Oct 19 07:49:06 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Main_GUI(object):
    def setupUi(self, Main_GUI):
        Main_GUI.setObjectName("Main_GUI")
        Main_GUI.resize(617, 680)
        Main_GUI.setMinimumSize(QtCore.QSize(0, 680))
        Main_GUI.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralWidget = QtWidgets.QWidget(Main_GUI)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(593, 500))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_process = QtWidgets.QWidget()
        self.tab_process.setObjectName("tab_process")
        self.process_tab_layout = QtWidgets.QVBoxLayout(self.tab_process)
        self.process_tab_layout.setObjectName("process_tab_layout")
        self.processSplitter = QtWidgets.QSplitter(self.tab_process)
        self.processSplitter.setOrientation(QtCore.Qt.Vertical)
        self.processSplitter.setObjectName("processSplitter")
        self.listbox = QtWidgets.QTableWidget(self.processSplitter)
        self.listbox.setMinimumSize(QtCore.QSize(0, 50))
        self.listbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listbox.setDragEnabled(True)
        self.listbox.setDragDropOverwriteMode(False)
        self.listbox.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listbox.setAlternatingRowColors(True)
        self.listbox.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listbox.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listbox.setShowGrid(True)
        self.listbox.setGridStyle(QtCore.Qt.DashLine)
        self.listbox.setWordWrap(False)
        self.listbox.setCornerButtonEnabled(True)
        self.listbox.setColumnCount(7)
        self.listbox.setObjectName("listbox")
        self.listbox.setColumnCount(7)
        self.listbox.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.listbox.setHorizontalHeaderItem(6, item)
        self.impListWidget = QtWidgets.QListWidget(self.processSplitter)
        self.impListWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.impListWidget.setObjectName("impListWidget")
        self.process_tab_layout.addWidget(self.processSplitter)
        self.tabWidget.addTab(self.tab_process, "")
        self.tab_registration = QtWidgets.QWidget()
        self.tab_registration.setObjectName("tab_registration")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_registration)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RegCalib_channelRefModeCombo = QtWidgets.QComboBox(self.tab_registration)
        self.RegCalib_channelRefModeCombo.setEnabled(True)
        self.RegCalib_channelRefModeCombo.setMinimumSize(QtCore.QSize(0, 0))
        self.RegCalib_channelRefModeCombo.setMaximumSize(QtCore.QSize(1606000, 16777215))
        self.RegCalib_channelRefModeCombo.setCurrentText("")
        self.RegCalib_channelRefModeCombo.setObjectName("RegCalib_channelRefModeCombo")
        self.gridLayout_3.addWidget(self.RegCalib_channelRefModeCombo, 8, 6, 1, 3)
        self.RegCalibPathLineEdit = QtWidgets.QLineEdit(self.tab_registration)
        self.RegCalibPathLineEdit.setEnabled(True)
        self.RegCalibPathLineEdit.setObjectName("RegCalibPathLineEdit")
        self.gridLayout_3.addWidget(self.RegCalibPathLineEdit, 0, 1, 1, 7)
        self.RegCalib_channelRefCombo = QtWidgets.QComboBox(self.tab_registration)
        self.RegCalib_channelRefCombo.setEnabled(True)
        self.RegCalib_channelRefCombo.setMaximumSize(QtCore.QSize(70, 16777215))
        self.RegCalib_channelRefCombo.setCurrentText("")
        self.RegCalib_channelRefCombo.setObjectName("RegCalib_channelRefCombo")
        self.gridLayout_3.addWidget(self.RegCalib_channelRefCombo, 8, 4, 1, 1)
        self.RegCalibRefChannelsLabel = QtWidgets.QLabel(self.tab_registration)
        self.RegCalibRefChannelsLabel.setEnabled(True)
        self.RegCalibRefChannelsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RegCalibRefChannelsLabel.setObjectName("RegCalibRefChannelsLabel")
        self.gridLayout_3.addWidget(self.RegCalibRefChannelsLabel, 3, 2, 1, 2)
        self.GenerateRegFileButton = QtWidgets.QPushButton(self.tab_registration)
        self.GenerateRegFileButton.setMinimumSize(QtCore.QSize(190, 0))
        self.GenerateRegFileButton.setObjectName("GenerateRegFileButton")
        self.gridLayout_3.addWidget(self.GenerateRegFileButton, 3, 0, 1, 2)
        self.RegCalibPathLabel = QtWidgets.QLabel(self.tab_registration)
        self.RegCalibPathLabel.setMinimumSize(QtCore.QSize(95, 0))
        self.RegCalibPathLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RegCalibPathLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.RegCalibPathLabel.setObjectName("RegCalibPathLabel")
        self.gridLayout_3.addWidget(self.RegCalibPathLabel, 0, 0, 1, 1)
        self.RegCalib_channelRefModeLabel = QtWidgets.QLabel(self.tab_registration)
        self.RegCalib_channelRefModeLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.RegCalib_channelRefModeLabel.setObjectName("RegCalib_channelRefModeLabel")
        self.gridLayout_3.addWidget(self.RegCalib_channelRefModeLabel, 8, 5, 1, 1)
        self.horizline_1 = QtWidgets.QFrame(self.tab_registration)
        self.horizline_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizline_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizline_1.setObjectName("horizline_1")
        self.gridLayout_3.addWidget(self.horizline_1, 4, 0, 1, 9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 9, 4, 1, 1)
        self.RegCalibPathLoadButton = QtWidgets.QPushButton(self.tab_registration)
        self.RegCalibPathLoadButton.setObjectName("RegCalibPathLoadButton")
        self.gridLayout_3.addWidget(self.RegCalibPathLoadButton, 0, 8, 1, 1)
        self.RegFilePathLoadButton = QtWidgets.QPushButton(self.tab_registration)
        self.RegFilePathLoadButton.setObjectName("RegFilePathLoadButton")
        self.gridLayout_3.addWidget(self.RegFilePathLoadButton, 6, 8, 1, 1)
        self.RegFilePathLabel = QtWidgets.QLabel(self.tab_registration)
        self.RegFilePathLabel.setMinimumSize(QtCore.QSize(105, 0))
        self.RegFilePathLabel.setObjectName("RegFilePathLabel")
        self.gridLayout_3.addWidget(self.RegFilePathLabel, 6, 0, 1, 1)
        self.RegFilePath = QtWidgets.QLineEdit(self.tab_registration)
        self.RegFilePath.setEnabled(True)
        self.RegFilePath.setText("")
        self.RegFilePath.setObjectName("RegFilePath")
        self.gridLayout_3.addWidget(self.RegFilePath, 6, 1, 1, 7)
        self.RegCalibPreviewButton = QtWidgets.QPushButton(self.tab_registration)
        self.RegCalibPreviewButton.setObjectName("RegCalibPreviewButton")
        self.gridLayout_3.addWidget(self.RegCalibPreviewButton, 8, 0, 1, 2)
        self.RegCalib_channelRefLabel = QtWidgets.QLabel(self.tab_registration)
        self.RegCalib_channelRefLabel.setEnabled(True)
        self.RegCalib_channelRefLabel.setObjectName("RegCalib_channelRefLabel")
        self.gridLayout_3.addWidget(self.RegCalib_channelRefLabel, 8, 2, 1, 2)
        self.BeadThresholdLabel = QtWidgets.QLabel(self.tab_registration)
        self.BeadThresholdLabel.setMinimumSize(QtCore.QSize(95, 0))
        self.BeadThresholdLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BeadThresholdLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BeadThresholdLabel.setObjectName("BeadThresholdLabel")
        self.gridLayout_3.addWidget(self.BeadThresholdLabel, 1, 0, 1, 1)
        self.RegCalibRefChannelsGroup = QtWidgets.QGroupBox(self.tab_registration)
        self.RegCalibRefChannelsGroup.setTitle("")
        self.RegCalibRefChannelsGroup.setObjectName("RegCalibRefChannelsGroup")
        self.RegCalibRefGroupLayout = QtWidgets.QHBoxLayout(self.RegCalibRefChannelsGroup)
        self.RegCalibRefGroupLayout.setContentsMargins(-1, 0, -1, 0)
        self.RegCalibRefGroupLayout.setObjectName("RegCalibRefGroupLayout")
        self.gridLayout_3.addWidget(self.RegCalibRefChannelsGroup, 3, 4, 1, 5)
        self.RegBeadThreshSpin = QtWidgets.QSpinBox(self.tab_registration)
        self.RegBeadThreshSpin.setEnabled(False)
        self.RegBeadThreshSpin.setMaximum(65536)
        self.RegBeadThreshSpin.setProperty("value", 1000)
        self.RegBeadThreshSpin.setObjectName("RegBeadThreshSpin")
        self.gridLayout_3.addWidget(self.RegBeadThreshSpin, 1, 1, 1, 1)
        self.RegMinBeadsLabel = QtWidgets.QLabel(self.tab_registration)
        self.RegMinBeadsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.RegMinBeadsLabel.setObjectName("RegMinBeadsLabel")
        self.gridLayout_3.addWidget(self.RegMinBeadsLabel, 1, 4, 1, 4)
        self.RegMinBeadsSpin = QtWidgets.QSpinBox(self.tab_registration)
        self.RegMinBeadsSpin.setMaximum(200)
        self.RegMinBeadsSpin.setProperty("value", 20)
        self.RegMinBeadsSpin.setObjectName("RegMinBeadsSpin")
        self.gridLayout_3.addWidget(self.RegMinBeadsSpin, 1, 8, 1, 1)
        self.RegAutoThreshCheckbox = QtWidgets.QCheckBox(self.tab_registration)
        self.RegAutoThreshCheckbox.setEnabled(True)
        self.RegAutoThreshCheckbox.setChecked(True)
        self.RegAutoThreshCheckbox.setObjectName("RegAutoThreshCheckbox")
        self.gridLayout_3.addWidget(self.RegAutoThreshCheckbox, 1, 2, 1, 2)
        self.tabWidget.addTab(self.tab_registration, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_config)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cudaDeconvPathLabel_2 = QtWidgets.QLabel(self.tab_config)
        self.cudaDeconvPathLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cudaDeconvPathLabel_2.setObjectName("cudaDeconvPathLabel_2")
        self.gridLayout_4.addWidget(self.cudaDeconvPathLabel_2, 0, 0, 1, 1)
        self.filenamePatternLabel = QtWidgets.QLabel(self.tab_config)
        self.filenamePatternLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filenamePatternLabel.setObjectName("filenamePatternLabel")
        self.gridLayout_4.addWidget(self.filenamePatternLabel, 2, 0, 1, 1)
        self.defaultValuesLabel = QtWidgets.QLabel(self.tab_config)
        self.defaultValuesLabel.setEnabled(True)
        self.defaultValuesLabel.setObjectName("defaultValuesLabel")
        self.gridLayout_4.addWidget(self.defaultValuesLabel, 4, 0, 1, 1)
        self.defaultDxLabel = QtWidgets.QLabel(self.tab_config)
        self.defaultDxLabel.setEnabled(False)
        self.defaultDxLabel.setObjectName("defaultDxLabel")
        self.gridLayout_4.addWidget(self.defaultDxLabel, 4, 1, 1, 1)
        self.defaultDxSpin = QtWidgets.QDoubleSpinBox(self.tab_config)
        self.defaultDxSpin.setEnabled(True)
        self.defaultDxSpin.setDecimals(3)
        self.defaultDxSpin.setSingleStep(0.01)
        self.defaultDxSpin.setProperty("value", 0.1)
        self.defaultDxSpin.setObjectName("defaultDxSpin")
        self.gridLayout_4.addWidget(self.defaultDxSpin, 4, 2, 1, 1)
        self.defaultDzLabel = QtWidgets.QLabel(self.tab_config)
        self.defaultDzLabel.setEnabled(False)
        self.defaultDzLabel.setObjectName("defaultDzLabel")
        self.gridLayout_4.addWidget(self.defaultDzLabel, 4, 3, 1, 1)
        self.defaultDzSpin = QtWidgets.QDoubleSpinBox(self.tab_config)
        self.defaultDzSpin.setEnabled(True)
        self.defaultDzSpin.setDecimals(3)
        self.defaultDzSpin.setSingleStep(0.01)
        self.defaultDzSpin.setProperty("value", 0.5)
        self.defaultDzSpin.setObjectName("defaultDzSpin")
        self.gridLayout_4.addWidget(self.defaultDzSpin, 4, 4, 1, 1)
        self.defaultAngleLabel = QtWidgets.QLabel(self.tab_config)
        self.defaultAngleLabel.setEnabled(False)
        self.defaultAngleLabel.setObjectName("defaultAngleLabel")
        self.gridLayout_4.addWidget(self.defaultAngleLabel, 4, 5, 1, 1)
        self.defaultAngleSpin = QtWidgets.QDoubleSpinBox(self.tab_config)
        self.defaultAngleSpin.setEnabled(True)
        self.defaultAngleSpin.setDecimals(1)
        self.defaultAngleSpin.setSingleStep(0.1)
        self.defaultAngleSpin.setProperty("value", 31.5)
        self.defaultAngleSpin.setObjectName("defaultAngleSpin")
        self.gridLayout_4.addWidget(self.defaultAngleSpin, 4, 6, 1, 1)
        self.genFlashParams = QtWidgets.QPushButton(self.tab_config)
        self.genFlashParams.setObjectName("genFlashParams")
        self.gridLayout_4.addWidget(self.genFlashParams, 5, 1, 1, 6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 600, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 4, 1, 1)
        self.disableSpimagineCheckBox = QtWidgets.QCheckBox(self.tab_config)
        self.disableSpimagineCheckBox.setChecked(False)
        self.disableSpimagineCheckBox.setObjectName("disableSpimagineCheckBox")
        self.gridLayout_4.addWidget(self.disableSpimagineCheckBox, 7, 1, 1, 6)
        self.previewBackendLabel = QtWidgets.QLabel(self.tab_config)
        self.previewBackendLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.previewBackendLabel.setObjectName("previewBackendLabel")
        self.gridLayout_4.addWidget(self.previewBackendLabel, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 600, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 9, 4, 1, 1)
        self.watchDirCheckBox = QtWidgets.QCheckBox(self.tab_config)
        self.watchDirCheckBox.setObjectName("watchDirCheckBox")
        self.gridLayout_4.addWidget(self.watchDirCheckBox, 10, 0, 1, 1)
        self.watchDirLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.watchDirLineEdit.setEnabled(False)
        self.watchDirLineEdit.setText("")
        self.watchDirLineEdit.setReadOnly(True)
        self.watchDirLineEdit.setObjectName("watchDirLineEdit")
        self.gridLayout_4.addWidget(self.watchDirLineEdit, 10, 1, 1, 6)
        self.watchDirToolButton = QtWidgets.QToolButton(self.tab_config)
        self.watchDirToolButton.setEnabled(False)
        self.watchDirToolButton.setObjectName("watchDirToolButton")
        self.gridLayout_4.addWidget(self.watchDirToolButton, 10, 7, 1, 1)
        self.filenamePatternLineEdit = QtWidgets.QLineEdit(self.tab_config)
        self.filenamePatternLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filenamePatternLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.filenamePatternLineEdit.setReadOnly(False)
        self.filenamePatternLineEdit.setObjectName("filenamePatternLineEdit")
        self.gridLayout_4.addWidget(self.filenamePatternLineEdit, 2, 1, 1, 6)
        self.gpusGroupBox = QtWidgets.QGroupBox(self.tab_config)
        self.gpusGroupBox.setTitle("")
        self.gpusGroupBox.setObjectName("gpusGroupBox")
        self.gpuGroupBoxLayout = QtWidgets.QHBoxLayout(self.gpusGroupBox)
        self.gpuGroupBoxLayout.setContentsMargins(-1, 2, -1, 2)
        self.gpuGroupBoxLayout.setObjectName("gpuGroupBoxLayout")
        self.gridLayout_4.addWidget(self.gpusGroupBox, 0, 1, 1, 6)
        self.previewBackendGroupBox = QtWidgets.QGroupBox(self.tab_config)
        self.previewBackendGroupBox.setTitle("")
        self.previewBackendGroupBox.setObjectName("previewBackendGroupBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.previewBackendGroupBox)
        self.horizontalLayout_10.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.prevBackendNapariRadio = QtWidgets.QRadioButton(self.previewBackendGroupBox)
        self.prevBackendNapariRadio.setChecked(True)
        self.prevBackendNapariRadio.setObjectName("prevBackendNapariRadio")
        self.horizontalLayout_10.addWidget(self.prevBackendNapariRadio)
        self.prevBackendSpimagineRadio = QtWidgets.QRadioButton(self.previewBackendGroupBox)
        self.prevBackendSpimagineRadio.setChecked(True)
        self.prevBackendSpimagineRadio.setObjectName("prevBackendSpimagineRadio")
        self.horizontalLayout_10.addWidget(self.prevBackendSpimagineRadio)
        self.prevBackendMatplotlibRadio = QtWidgets.QRadioButton(self.previewBackendGroupBox)
        self.prevBackendMatplotlibRadio.setObjectName("prevBackendMatplotlibRadio")
        self.horizontalLayout_10.addWidget(self.prevBackendMatplotlibRadio)
        self.gridLayout_4.addWidget(self.previewBackendGroupBox, 8, 1, 1, 6)
        self.tabWidget.addTab(self.tab_config, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_log)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log = QtWidgets.QTextEdit(self.tab_log)
        self.log.setAutoFillBackground(False)
        self.log.setStyleSheet("")
        self.log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.log.setLineWidth(2)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.tabWidget.addTab(self.tab_log, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.previewProcessButtonFrame = QtWidgets.QFrame(self.centralWidget)
        self.previewProcessButtonFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.previewProcessButtonFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.previewProcessButtonFrame.setObjectName("previewProcessButtonFrame")
        self.processButtonLayout = QtWidgets.QHBoxLayout(self.previewProcessButtonFrame)
        self.processButtonLayout.setContentsMargins(-1, 0, -1, 0)
        self.processButtonLayout.setObjectName("processButtonLayout")
        self.previewButton = QtWidgets.QPushButton(self.previewProcessButtonFrame)
        self.previewButton.setEnabled(True)
        self.previewButton.setMinimumSize(QtCore.QSize(0, 0))
        self.previewButton.setAutoDefault(True)
        self.previewButton.setDefault(False)
        self.previewButton.setFlat(False)
        self.previewButton.setObjectName("previewButton")
        self.processButtonLayout.addWidget(self.previewButton)
        self.previewCRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.previewCRangeLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.previewCRangeLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.previewCRangeLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.previewCRangeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.previewCRangeLineEdit.setObjectName("previewCRangeLineEdit")
        self.processButtonLayout.addWidget(self.previewCRangeLineEdit)
        self.previewTRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.previewTRangeLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.previewTRangeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.previewTRangeLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.previewTRangeLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.previewTRangeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.previewTRangeLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.previewTRangeLineEdit.setClearButtonEnabled(False)
        self.previewTRangeLineEdit.setObjectName("previewTRangeLineEdit")
        self.processButtonLayout.addWidget(self.previewTRangeLineEdit)
        self.line = QtWidgets.QFrame(self.previewProcessButtonFrame)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.processButtonLayout.addWidget(self.line)
        self.processButton = QtWidgets.QPushButton(self.previewProcessButtonFrame)
        self.processButton.setMinimumSize(QtCore.QSize(0, 0))
        self.processButton.setObjectName("processButton")
        self.processButtonLayout.addWidget(self.processButton)
        self.processCRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.processCRangeLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.processCRangeLineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.processCRangeLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.processCRangeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.processCRangeLineEdit.setObjectName("processCRangeLineEdit")
        self.processButtonLayout.addWidget(self.processCRangeLineEdit)
        self.processTRangeLineEdit = QtWidgets.QLineEdit(self.previewProcessButtonFrame)
        self.processTRangeLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.processTRangeLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.processTRangeLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.processTRangeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.processTRangeLineEdit.setObjectName("processTRangeLineEdit")
        self.processButtonLayout.addWidget(self.processTRangeLineEdit)
        self.verticalLayout_4.addWidget(self.previewProcessButtonFrame)
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"  border: 1px solid grey;\n"
"  border-radius: 3px;\n"
"  height: 20px;\n"
"  margin: 0px 0px 0px 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk:horizontal {\n"
"  background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5, stop: 0 #484DE7, stop: 1 #787DFF);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.clock = QtWidgets.QLCDNumber(self.centralWidget)
        self.clock.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.clock.setFont(font)
        self.clock.setStyleSheet("")
        self.clock.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.clock.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.clock.setLineWidth(1)
        self.clock.setMidLineWidth(0)
        self.clock.setSmallDecimalPoint(True)
        self.clock.setDigitCount(8)
        self.clock.setMode(QtWidgets.QLCDNumber.Dec)
        self.clock.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.clock.setObjectName("clock")
        self.progressLayout.addWidget(self.clock)
        self.verticalLayout_4.addLayout(self.progressLayout)
        Main_GUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuProcess = QtWidgets.QMenu(self.menuBar)
        self.menuProcess.setObjectName("menuProcess")
        self.menuMOSAICpy = QtWidgets.QMenu(self.menuBar)
        self.menuMOSAICpy.setObjectName("menuMOSAICpy")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        Main_GUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Main_GUI)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setObjectName("mainToolBar")
        Main_GUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Main_GUI)
        self.statusBar.setMinimumSize(QtCore.QSize(0, 30))
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        Main_GUI.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(Main_GUI)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPreview = QtWidgets.QAction(Main_GUI)
        self.actionPreview.setObjectName("actionPreview")
        self.actionRun = QtWidgets.QAction(Main_GUI)
        self.actionRun.setObjectName("actionRun")
        self.actionAbort = QtWidgets.QAction(Main_GUI)
        self.actionAbort.setEnabled(False)
        self.actionAbort.setObjectName("actionAbort")
        self.actionOpen_LLSdir = QtWidgets.QAction(Main_GUI)
        self.actionOpen_LLSdir.setObjectName("actionOpen_LLSdir")
        self.actionSave_Settings_as_Default = QtWidgets.QAction(Main_GUI)
        self.actionSave_Settings_as_Default.setObjectName("actionSave_Settings_as_Default")
        self.actionLoad_Default_Settings = QtWidgets.QAction(Main_GUI)
        self.actionLoad_Default_Settings.setObjectName("actionLoad_Default_Settings")
        self.actionReduce_to_Raw = QtWidgets.QAction(Main_GUI)
        self.actionReduce_to_Raw.setObjectName("actionReduce_to_Raw")
        self.actionCompress_Folder = QtWidgets.QAction(Main_GUI)
        self.actionCompress_Folder.setObjectName("actionCompress_Folder")
        self.actionDecompress_Folder = QtWidgets.QAction(Main_GUI)
        self.actionDecompress_Folder.setObjectName("actionDecompress_Folder")
        self.actionConcatenate = QtWidgets.QAction(Main_GUI)
        self.actionConcatenate.setObjectName("actionConcatenate")
        self.actionRename_Scripted = QtWidgets.QAction(Main_GUI)
        self.actionRename_Scripted.setObjectName("actionRename_Scripted")
        self.actionClose_All_Previews = QtWidgets.QAction(Main_GUI)
        self.actionClose_All_Previews.setObjectName("actionClose_All_Previews")
        self.actionAbout_MOSAICpy = QtWidgets.QAction(Main_GUI)
        self.actionAbout_MOSAICpy.setObjectName("actionAbout_MOSAICpy")
        self.actionFreeze = QtWidgets.QAction(Main_GUI)
        self.actionFreeze.setObjectName("actionFreeze")
        self.actionHelp = QtWidgets.QAction(Main_GUI)
        self.actionHelp.setObjectName("actionHelp")
        self.actionCamera_Calibration = QtWidgets.QAction(Main_GUI)
        self.actionCamera_Calibration.setObjectName("actionCamera_Calibration")
        self.actionRename_Iters = QtWidgets.QAction(Main_GUI)
        self.actionRename_Iters.setObjectName("actionRename_Iters")
        self.actionUndo_Rename_Iters = QtWidgets.QAction(Main_GUI)
        self.actionUndo_Rename_Iters.setObjectName("actionUndo_Rename_Iters")
        self.actionReveal = QtWidgets.QAction(Main_GUI)
        self.actionReveal.setObjectName("actionReveal")
        self.actionMerge_MIPs_from_folder = QtWidgets.QAction(Main_GUI)
        self.actionMerge_MIPs_from_folder.setObjectName("actionMerge_MIPs_from_folder")
        self.menuFile.addAction(self.actionOpen_LLSdir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Settings_as_Default)
        self.menuFile.addAction(self.actionLoad_Default_Settings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionClose_All_Previews)
        self.menuProcess.addAction(self.actionPreview)
        self.menuProcess.addAction(self.actionRun)
        self.menuProcess.addAction(self.actionAbort)
        self.menuProcess.addSeparator()
        self.menuProcess.addAction(self.actionRename_Iters)
        self.menuProcess.addAction(self.actionUndo_Rename_Iters)
        self.menuMOSAICpy.addAction(self.actionAbout_MOSAICpy)
        self.menuMOSAICpy.addAction(self.actionHelp)
        self.menuTools.addAction(self.actionCamera_Calibration)
        self.menuTools.addAction(self.actionMerge_MIPs_from_folder)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuProcess.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuMOSAICpy.menuAction())
        self.mainToolBar.addAction(self.actionReduce_to_Raw)
        self.mainToolBar.addAction(self.actionCompress_Folder)
        self.mainToolBar.addAction(self.actionDecompress_Folder)
        self.mainToolBar.addAction(self.actionFreeze)
        self.mainToolBar.addAction(self.actionConcatenate)
        self.mainToolBar.addAction(self.actionRename_Scripted)
        self.mainToolBar.addAction(self.actionReveal)
        self.RegCalibPathLabel.setBuddy(self.RegCalibPathLineEdit)
        self.RegCalib_channelRefModeLabel.setBuddy(self.RegCalib_channelRefModeCombo)
        self.RegFilePathLabel.setBuddy(self.RegFilePath)
        self.RegCalib_channelRefLabel.setBuddy(self.RegCalib_channelRefCombo)
        self.BeadThresholdLabel.setBuddy(self.RegBeadThreshSpin)
        self.RegMinBeadsLabel.setBuddy(self.RegMinBeadsSpin)

        self.retranslateUi(Main_GUI)
        self.tabWidget.setCurrentIndex(0)
        self.RegCalib_channelRefModeCombo.setCurrentIndex(-1)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered(bool)"), Main_GUI.close)
        QtCore.QObject.connect(self.watchDirCheckBox, QtCore.SIGNAL("toggled(bool)"), self.watchDirToolButton.setEnabled)
        QtCore.QObject.connect(self.watchDirCheckBox, QtCore.SIGNAL("toggled(bool)"), self.watchDirLineEdit.setEnabled)
        QtCore.QObject.connect(self.RegAutoThreshCheckbox, QtCore.SIGNAL("toggled(bool)"), self.RegBeadThreshSpin.setDisabled)
        QtCore.QObject.connect(self.RegAutoThreshCheckbox, QtCore.SIGNAL("toggled(bool)"), self.RegMinBeadsLabel.setEnabled)
        QtCore.QObject.connect(self.RegAutoThreshCheckbox, QtCore.SIGNAL("toggled(bool)"), self.RegMinBeadsSpin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Main_GUI)

    def retranslateUi(self, Main_GUI):
        Main_GUI.setWindowTitle(QtWidgets.QApplication.translate("Main_GUI", "Main_GUI", None, -1))
        self.listbox.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Drag and drop LLS experiment folders\n"
"(containing a Settings.txt file) here, to\n"
"add to the processing queue. Select\n"
"and press delete to remove.\n"
"Press process button below when ready.", None, -1))
        self.listbox.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Main_GUI", "basename", None, -1))
        self.listbox.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Main_GUI", "nC", None, -1))
        self.listbox.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Main_GUI", "nT", None, -1))
        self.listbox.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("Main_GUI", "nX", None, -1))
        self.listbox.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("Main_GUI", "nY", None, -1))
        self.listbox.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("Main_GUI", "nZ", None, -1))
        self.listbox.horizontalHeaderItem(6).setText(QtWidgets.QApplication.translate("Main_GUI", "desQ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_process), QtWidgets.QApplication.translate("Main_GUI", "Process", None, -1))
        self.RegCalib_channelRefModeCombo.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Type of registration to perform:\n"
"Translation=shift only\n"
"Rigid=Shift and rotation\n"
"Similarity=Rigid plus scaling\n"
"Affine=Translation, Rotation, Scaling, Shear\n"
"2-step=Affine in XY, Rigid in Z\n"
"CPD=Coherent Point Drift algorithm\n"
"(Myronenko, 2010)", None, -1))
        self.RegCalibPathLineEdit.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Specify folder with calibration (e.g. tetraspeck\n"
"bead) images acquired in each channel.", None, -1))
        self.RegCalibPathLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", " Folder with mult-channel fiducial stacks...", None, -1))
        self.RegCalib_channelRefCombo.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Reference channel to which to register\n"
"(this channel will not change)", None, -1))
        self.RegCalibRefChannelsLabel.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Reference channel to which to register\n"
"(this channel will not change)", None, -1))
        self.RegCalibRefChannelsLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Ref Channels:", None, -1))
        self.GenerateRegFileButton.setText(QtWidgets.QApplication.translate("Main_GUI", "Generate Registration File", None, -1))
        self.RegCalibPathLabel.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Specify folder with calibration (e.g. tetraspeck\n"
"bead) images acquired in each channel.", None, -1))
        self.RegCalibPathLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Fiducial Data:", None, -1))
        self.RegCalib_channelRefModeLabel.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Type of registration to perform:\n"
"Translation=shift only\n"
"Rigid=Shift and rotation\n"
"Similarity=Rigid plus scaling\n"
"Affine=Translation, Rotation, Scaling, Shear\n"
"2-step=Affine in XY, Rigid in Z\n"
"CPD=Coherent Point Drift algorithm\n"
"(Myronenko, 2010)", None, -1))
        self.RegCalib_channelRefModeLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Mode:", None, -1))
        self.RegCalibPathLoadButton.setText(QtWidgets.QApplication.translate("Main_GUI", "load", None, -1))
        self.RegFilePathLoadButton.setText(QtWidgets.QApplication.translate("Main_GUI", "load", None, -1))
        self.RegFilePathLabel.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Specify folder with calibration (e.g. tetraspeck\n"
"bead) images acquired in each channel.", None, -1))
        self.RegFilePathLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Registration File:", None, -1))
        self.RegFilePath.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Specify folder with calibration (e.g. tetraspeck\n"
"bead) images acquired in each channel.", None, -1))
        self.RegFilePath.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", " Registration Tform file...", None, -1))
        self.RegCalibPreviewButton.setText(QtWidgets.QApplication.translate("Main_GUI", "Register Fiducial Data", None, -1))
        self.RegCalib_channelRefLabel.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Reference channel to which to register\n"
"(this channel will not change)", None, -1))
        self.RegCalib_channelRefLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Ref Channel:", None, -1))
        self.BeadThresholdLabel.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Specify folder with calibration (e.g. tetraspeck\n"
"bead) images acquired in each channel.", None, -1))
        self.BeadThresholdLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Bead Threshold:", None, -1))
        self.RegMinBeadsLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Min number of beads:", None, -1))
        self.RegAutoThreshCheckbox.setText(QtWidgets.QApplication.translate("Main_GUI", "Autodetect", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_registration), QtWidgets.QApplication.translate("Main_GUI", "Registration", None, -1))
        self.cudaDeconvPathLabel_2.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Toggle the GPUs that you want to use for processing.\n"
" Work will be distributed among them", None, -1))
        self.cudaDeconvPathLabel_2.setText(QtWidgets.QApplication.translate("Main_GUI", "GPUs", None, -1))
        self.filenamePatternLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "filename pattern:", None, -1))
        self.defaultValuesLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "default values:", None, -1))
        self.defaultDxLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "dx:", None, -1))
        self.defaultDzLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "dz:", None, -1))
        self.defaultAngleLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "angle:", None, -1))
        self.genFlashParams.setText(QtWidgets.QApplication.translate("Main_GUI", "Generate Camera Calibration File", None, -1))
        self.disableSpimagineCheckBox.setText(QtWidgets.QApplication.translate("Main_GUI", "Disable spimagine import (in case of WinError on Preview)", None, -1))
        self.previewBackendLabel.setText(QtWidgets.QApplication.translate("Main_GUI", "Preview Type", None, -1))
        self.watchDirCheckBox.setText(QtWidgets.QApplication.translate("Main_GUI", "Watch Directory:", None, -1))
        self.watchDirLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", "New items in watched folder will be automatically processed.", None, -1))
        self.watchDirToolButton.setText(QtWidgets.QApplication.translate("Main_GUI", "...", None, -1))
        self.filenamePatternLineEdit.setText(QtWidgets.QApplication.translate("Main_GUI", "{basename}_ch{channel:d}_stack{stack:d}_{wave:d}nm_{reltime:d}msec_{abstime:d}msecAbs{}", None, -1))
        self.filenamePatternLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", "filename pattern", None, -1))
        self.gpusGroupBox.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Toggle the GPUs that you want to use for processing.\n"
" Work will be distributed among them", None, -1))
        self.prevBackendNapariRadio.setText(QtWidgets.QApplication.translate("Main_GUI", "napari", None, -1))
        self.prevBackendSpimagineRadio.setText(QtWidgets.QApplication.translate("Main_GUI", "spimagine", None, -1))
        self.prevBackendMatplotlibRadio.setText(QtWidgets.QApplication.translate("Main_GUI", "matplotlib", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), QtWidgets.QApplication.translate("Main_GUI", "Config", None, -1))
        self.log.setHtml(QtWidgets.QApplication.translate("Main_GUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><br /></p></body></html>", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), QtWidgets.QApplication.translate("Main_GUI", "Log", None, -1))
        self.previewButton.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Preview the highlighted dataset with the current settings", None, -1))
        self.previewButton.setText(QtWidgets.QApplication.translate("Main_GUI", "Preview", None, -1))
        self.previewCRangeLineEdit.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of channels to preview. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes. <br>For instance: \'0,2-3\'<br>NOTE: channels are zero-indexed</span></p></body></html>", None, -1))
        self.previewCRangeLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", "channels", None, -1))
        self.previewTRangeLineEdit.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of timepoints to preview. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes.<br>For instance: \'0,3,5-10,15-30-3,40\'<br>NOTE: time is zero-indexed</span></p></body></html>", None, -1))
        self.previewTRangeLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", "time", None, -1))
        self.processButton.setText(QtWidgets.QApplication.translate("Main_GUI", "Process", None, -1))
        self.processCRangeLineEdit.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of channels to preview. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes. <br>For instance: \'0,2-3\'<br>NOTE: channels are zero-indexed</span></p></body></html>", None, -1))
        self.processCRangeLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", "channels", None, -1))
        self.processTRangeLineEdit.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "<html><head/><body><p><span style=\" font-size:12pt;\">a string can be used to dictate a subset of timepoints to process. Separate list items with commas, and &quot;start-stop-step&quot; items with dashes.<br>For instance: \'0,3,5-10,15-30-3,40\'<br>NOTE: time is zero-indexed</span></p></body></html>", None, -1))
        self.processTRangeLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Main_GUI", "time", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("Main_GUI", "File", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("Main_GUI", "View", None, -1))
        self.menuProcess.setTitle(QtWidgets.QApplication.translate("Main_GUI", "Process", None, -1))
        self.menuMOSAICpy.setTitle(QtWidgets.QApplication.translate("Main_GUI", "MOSAICpy", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("Main_GUI", "Tools", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("Main_GUI", "Quit", None, -1))
        self.actionQuit.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+Q", None, -1))
        self.actionPreview.setText(QtWidgets.QApplication.translate("Main_GUI", "Preview", None, -1))
        self.actionPreview.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+P", None, -1))
        self.actionRun.setText(QtWidgets.QApplication.translate("Main_GUI", "Run", None, -1))
        self.actionRun.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+R", None, -1))
        self.actionAbort.setText(QtWidgets.QApplication.translate("Main_GUI", "Abort", None, -1))
        self.actionAbort.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+X", None, -1))
        self.actionOpen_LLSdir.setText(QtWidgets.QApplication.translate("Main_GUI", "Open LLSdir", None, -1))
        self.actionOpen_LLSdir.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+O", None, -1))
        self.actionSave_Settings_as_Default.setText(QtWidgets.QApplication.translate("Main_GUI", "Save Settings as Default", None, -1))
        self.actionSave_Settings_as_Default.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+S", None, -1))
        self.actionLoad_Default_Settings.setText(QtWidgets.QApplication.translate("Main_GUI", "Load Default Settings", None, -1))
        self.actionLoad_Default_Settings.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+D", None, -1))
        self.actionReduce_to_Raw.setText(QtWidgets.QApplication.translate("Main_GUI", "Reduce to Raw", None, -1))
        self.actionReduce_to_Raw.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Remove all processed data from selected folder\n"
"and restore folder to it\'s original state\n"
"(immediately after acquisition)", None, -1))
        self.actionCompress_Folder.setText(QtWidgets.QApplication.translate("Main_GUI", "Compress Raw", None, -1))
        self.actionCompress_Folder.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Compress raw data in selected folder", None, -1))
        self.actionDecompress_Folder.setText(QtWidgets.QApplication.translate("Main_GUI", "Decompress Raw", None, -1))
        self.actionConcatenate.setText(QtWidgets.QApplication.translate("Main_GUI", "Concatenate", None, -1))
        self.actionConcatenate.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Merge selected folders into single LLSdir", None, -1))
        self.actionRename_Scripted.setText(QtWidgets.QApplication.translate("Main_GUI", "Rename Scripted", None, -1))
        self.actionRename_Scripted.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Rename \"Iter_\" files in an LLSdir acquired with Script Editor", None, -1))
        self.actionClose_All_Previews.setText(QtWidgets.QApplication.translate("Main_GUI", "Close All Previews", None, -1))
        self.actionClose_All_Previews.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+Shift+W", None, -1))
        self.actionAbout_MOSAICpy.setText(QtWidgets.QApplication.translate("Main_GUI", "About MOSAICpy", None, -1))
        self.actionFreeze.setText(QtWidgets.QApplication.translate("Main_GUI", "Freeze", None, -1))
        self.actionFreeze.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Delete all processed data, and compress raw data for storage", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("Main_GUI", "Help", None, -1))
        self.actionCamera_Calibration.setText(QtWidgets.QApplication.translate("Main_GUI", "Camera Calibration", None, -1))
        self.actionRename_Iters.setText(QtWidgets.QApplication.translate("Main_GUI", "Rename \'Iters_\'", None, -1))
        self.actionRename_Iters.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Rename files acquired with Script Editor mode, containing \'Iters_\'", None, -1))
        self.actionUndo_Rename_Iters.setText(QtWidgets.QApplication.translate("Main_GUI", "Undo Rename \'Iters_\'", None, -1))
        self.actionReveal.setText(QtWidgets.QApplication.translate("Main_GUI", "Reveal", None, -1))
        self.actionReveal.setToolTip(QtWidgets.QApplication.translate("Main_GUI", "Reveal Item in Explorer/Finder", None, -1))
        self.actionReveal.setShortcut(QtWidgets.QApplication.translate("Main_GUI", "Ctrl+Shift+O", None, -1))
        self.actionMerge_MIPs_from_folder.setText(QtWidgets.QApplication.translate("Main_GUI", "Merge MIPs", None, -1))

